export const CHARACTERS = {
  CREATE_CHARACTER: 'CREATE_CHARACTER',
  CREATE_CHARACTER_FULFILLED: 'CREATE_CHARACTER_FULFILLED',
  CREATE_CHARACTER_REJECTED: 'CREATE_CHARACTER_REJECTED',
  UPDATE_CHARACTER: 'UPDATE_CHARACTER',
  DELETE_CHARACTER: 'DELETE_CHARACTER',
  FILTER_CHARACTERS: 'FILTER_CHARACTERS',
  FILTER_CHARACTERS_FULFILLED: 'FILTER_CHARACTERS_FULFILLED',
  FILTER_CHARACTERS_REJECTED: 'FILTER_CHARACTERS_REJECTED'
};

export const CHARACTER_FILTERS = {
  ALL_CHARACTERS: 'ALL_CHARACTERS',
  VILLAIN_CHARACTERS: 'VILLAIN_CHARACTERS',
  HERO_CHARACTERS: 'HERO_CHARACTERS'
};