export default {

  CHARACTERS: {
    CREATE_CHARACTER: 'CREATE_CHARACTER',
    UPDATE_CHARACTER: 'UPDATE_CHARACTER',
    DELETE_CHARACTER: 'DELETE_CHARACTER',
    FILTER_CHARACTERS: 'FILTER_CHARACTERS'
  },

  CHARACTER_FILTERS: {
    ALL_CHARACTERS: 'ALL_CHARACTERS',
    VILLAIN_CHARACTERS: 'VILLAIN_CHARACTERS',
    HERO_CHARACTERS: 'HERO_CHARACTERS'
  }
}